
1. You are provided the titanic dataset. Load the dataset and perform splitting into training and test sets with 70:30 ratio randomly using test train split.
2. Use the Logistic regression created from scratch (from the prev question) in this question as well.
3. Data cleaning plays a major role in this question. Report all the methods used by you in the ipynb.

--> 

i. Check for missing values

ii. Drop Columns & Handle missing values

iii. Create dummies for categorical features

you are free to perform other data cleaning to improve your results.



4. Report accuracy score, Confusion matrix, heat map, classifiaction report and any other metrics you feel useful.

dataset link : 
https://iiitaphyd-my.sharepoint.com/:f:/g/personal/apurva_jadhav_students_iiit_ac_in/Eictt5_qmoxNqezgQQiMWeIBph4sxlfA6jWAJNPnV2SF9Q?e=mQmYN0 

(titanic.csv)


In [166]:
import pandas as pd
import numpy as np
data = pd.read_csv('Logistic_Regression_dataset/titanic.csv')

In [180]:
data.describe()
x_l = data.drop(['Survived','Ticket','Cabin','Name','PassengerId'],axis=1)
y_l = data['Survived']

sex_dict = {'female':0,'male':1}
x_l['Sex'] = x_l.Sex.map(sex_dict)

emb_dict = {'S':0,'C':1,'Q':2}
x_l['Embarked'] = x_l.Embarked.map(emb_dict)

x_l, y_l

(     Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
 0         3    1  22.0      1      0   7.2500       0.0
 1         1    0  38.0      1      0  71.2833       1.0
 2         3    0  26.0      0      0   7.9250       0.0
 3         1    0  35.0      1      0  53.1000       0.0
 4         3    1  35.0      0      0   8.0500       0.0
 ..      ...  ...   ...    ...    ...      ...       ...
 886       2    1  27.0      0      0  13.0000       0.0
 887       1    0  19.0      0      0  30.0000       0.0
 888       3    0   NaN      1      2  23.4500       0.0
 889       1    1  26.0      0      0  30.0000       1.0
 890       3    1  32.0      0      0   7.7500       2.0
 
 [891 rows x 7 columns],
 0      0
 1      1
 2      1
 3      1
 4      0
       ..
 886    0
 887    1
 888    0
 889    1
 890    0
 Name: Survived, Length: 891, dtype: int64)

In [181]:
x_l = x_l.to_numpy()
y_l = y_l.to_numpy()
x_l = np.nan_to_num(x_l)

x_l = x_l / x_l.max(axis=0)
x_l

array([[1.        , 1.        , 0.275     , ..., 0.        , 0.01415106,
        0.        ],
       [0.33333333, 0.        , 0.475     , ..., 0.        , 0.13913574,
        0.5       ],
       [1.        , 0.        , 0.325     , ..., 0.        , 0.01546857,
        0.        ],
       ...,
       [1.        , 0.        , 0.        , ..., 0.33333333, 0.04577135,
        0.        ],
       [0.33333333, 1.        , 0.325     , ..., 0.        , 0.0585561 ,
        0.5       ],
       [1.        , 1.        , 0.4       , ..., 0.        , 0.01512699,
        1.        ]])

In [182]:
from sklearn.model_selection import train_test_split

trainX, testX, trainy, testy = train_test_split(x_l, y_l.reshape(y_l.shape[0]), test_size=0.3, random_state=13)

In [183]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def diff_g(w,x,y):
    y_minus_sigmoid_wtx = sigmoid(np.dot(x,w)) - y
    return np.dot(x.T,y_minus_sigmoid_wtx)

def gradient_descent(x,y, num_iterations = 10000, learning_rate = 0.01):
    w = np.zeros(x.shape[1])
    for i in range(num_iterations):
        w = w - (learning_rate * diff_g(w,x,y))
    return w

def get_w_after_training(x,y):
    x = np.c_[x, np.ones(x.shape[0])]
    return gradient_descent(x,y)

def predict(w,x):
    x = np.c_[x, np.ones(x.shape[0])]
#     print(np.dot(w.T,x.T))
    sigm = sigmoid(np.dot(w.T,x.T))
    sigm[sigm > 0.5] = 1
    sigm[sigm <= 0.5] = 0
    return sigm

In [184]:
w = get_w_after_training(trainX,trainy)
w

array([-2.94575501, -2.80066812, -1.57976994, -3.02128797,  0.13927092,
        1.20630018,  0.49361807,  3.97373284])

In [185]:
predicted = predict(w,testX)

In [201]:
accuracy_score = (testy==predicted).mean()*100
print("Accuracy Score = ", accuracy_score)

Accuracy Score =  77.98507462686567


In [205]:
from sklearn.metrics import confusion_matrix, classification_report
print("Confusion Matrix :\n\n",confusion_matrix(testy, predicted))

Confusion Matrix :

 [[139  32]
 [ 27  70]]


In [206]:
print("Classification Report :\n\n",classification_report(testy, predicted))

Classification Report :

               precision    recall  f1-score   support

           0       0.84      0.81      0.82       171
           1       0.69      0.72      0.70        97

    accuracy                           0.78       268
   macro avg       0.76      0.77      0.76       268
weighted avg       0.78      0.78      0.78       268

